title: "Catgirl Engine"

# Theme Instructions: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
theme: jekyll-theme-midnight
